### ISSUE TITLE
Its not an Issue, its more like "aesthetics". :)

### ISSUE THREAD

**Issue by HellGateAI** [Lucksi/Mr.Holmes#10]
Hey Buddy,

great Work and a great Tool, thanks for sharing it. For the English Version you wrote a function named "(4)CONFIGURAZIONE",
but that Word is a combination from English and Italian, change it to "CONFIGURATION" and you got fixed it. : )
Have a nice Day and close that Issue post whenever you want.

Greetz

**Comment by Lucksi** [comment]
Thank you man t was a Typo i will fix it :)
