### ISSUE TITLE
/Site_lists/Username/site_list.json

### ISSUE THREAD

**Issue by JeroCod** [Lucksi/Mr.Holmes#12]
Ciao,
Ottimo lavoro. Mr.Holmes è uno strumento che uso spesso nella mia ricerca.
Lascia che ti faccia una domanda.
Vorrei regionalizzare le mie indagini per restringere il mio campo di ricerca. Renderle più precise.
ho modificato e cambiato siti in _Mr.Holmes/Site_lists/Username/site_list.json_.
Ma questo rende il sig. Holmes instabile e non funziona. Esiste una procedura speciale da seguire per questo o è impossibile?

**Comment by Lucksi** [comment]
Ciao, innanzitutto tutto ti ringrazio per il complimento, purtroppo non è possibile modificare il file site.json senza che ci possa essere qualche errore al momento
