### ISSUE TITLE
Mr.Holmes/Lang/french.json

### ISSUE THREAD

**Issue by JeroCod** [Lucksi/Mr.Holmes#13]
Ti aiuterò con la traduzione in francese :)

**Comment by Lucksi** [comment]
Beh grazie mille anche perché non sono più tutta sta cifra in francese :)

**Comment by JeroCod** [comment]
Ecco il file in francese :)
[french.json.zip](https://github.com/Lucksi/Mr.Holmes/files/10805841/french.json.zip)
