### ISSUE TITLE
Ecco il file in francese :)

### ISSUE THREAD

**Issue by JeroCod** [Lucksi/Mr.Holmes#15]
Ecco il file in francese :)
[french.json.zip](https://github.com/Lucksi/Mr.Holmes/files/10805841/french.json.zip)

_Originally posted by @JeroCod in https://github.com/Lucksi/Mr.Holmes/issues/13#issuecomment-1440311103_

**Comment by Lucksi** [comment]
Grazie mille per l'aiuto :)
