### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by khan94-hacker** [Lucksi/Mr.Holmes#21]
This command is not working
proot error: 'pip3' not found (root = /, cwd = /data/data/com.termux/files/home/Mr.Holmes, $PATH=/data/data/com.termux/files/usr/bin)
fatal error: see `proot --help`.

**Comment by Lucksi** [comment]
That's strange what version of termux are you using?

**Comment by khan94-hacker** [comment]
I am using 0.118.0 version of termux.

**Comment by Lucksi** [comment]
Mh try to do it directly on the command line, alternatively if it won't work try: pip3 install - r requirements.txt
