### ISSUE TITLE
No module named 'pyqrcode'

### ISSUE THREAD

**Issue by AngmarLord** [Lucksi/Mr.Holmes#25]
Complains on Windows that pyqrcode module isn't found. I have checked it, but pyqrcode is definitely present. I try and install it manually, using pip either with requirements.txt or even standalone, and they always say pyqrcode is present and there is nothing to upgrade. Yet, the launch fails.

The error occurs here - 
\Core\Support\FileTransfer.py", line 11, in <module>
    import pyqrcode
ModuleNotFoundError: No module named 'pyqrcode'

**Comment by Lechatdu17** [comment]
I’m not sure it will work but try this: " pip install pyqrcode "
