### ISSUE TITLE
Não está funcionando 

### ISSUE THREAD

**Issue by N1NGU3M** [Lucksi/Mr.Holmes#28]
![Screenshot_20230703-182107](https://github.com/Lucksi/Mr.Holmes/assets/138530921/ed213a9b-ce1d-4099-980c-516146609655) 
#

**Comment by Lucksi** [comment]
Hello, has the installation process been completed correctly?

**Comment by N1NGU3M** [comment]
Yes


Em seg., 3 de jul. de 2023 18:46, Luca Garofalo ***@***.***>
escreveu:

**Comment by Lucksi** [comment]
Apparently is a proxy miss configuration have you done the auto installer mode?
