### ISSUE TITLE
Problem with local variable "conf"

### ISSUE THREAD

**Issue by mendinone** [Lucksi/Mr.Holmes#29]
![Captura desde 2023-08-16 16-50-28](https://github.com/Lucksi/Mr.Holmes/assets/142281472/d4fc9f56-1d29-41d9-a529-82e47ee967ec)
![Captura desde 2023-08-16 16-53-35](https://github.com/Lucksi/Mr.Holmes/assets/142281472/17c88509-3c43-4834-984c-5dc38968a45e)

**Comment by Lucksi** [comment]
Hi, that's strange have you done the installation process?

**Comment by mendinone** [comment]
Yes of course

**Comment by Lucksi** [comment]
Can you try to execute the program from the terminal with the command python3 Mr.Holmes.py?

**Comment by Lucksi** [comment]
oh no okay you have already done it sorry

**Comment by Lucksi** [comment]
Can you see if there is a file in the Display folder called Display.txt?

**Comment by mendinone** [comment]
Nope

**Comment by Lucksi** [comment]
What Installation have you done? the automatic one ?

**Comment by mendinone** [comment]
First, I tried the automatic installation, then the manual one, there were always the same errors

**Comment by Lucksi** [comment]
Ok it was a code problem now it should be fixed please ley me know :)

**Comment by mendinone** [comment]
Ok lemme try

**Comment by mendinone** [comment]
![20230816_173359.jpg](https://github.com/Lucksi/Mr.Holmes/assets/142281472/11a8728d-b08d-459e-9587-0ef29b551ecc)

This is while the installation

**Comment by Lucksi** [comment]
Ok i have update the installer again

**Comment by Lucksi** [comment]
now it should work (i hope so)

**Comment by Lucksi** [comment]
let me know the result :)

**Comment by mendinone** [comment]
![20230816_174538.jpg](https://github.com/Lucksi/Mr.Holmes/assets/142281472/264b2f7c-424c-4a08-8c83-098c744c6d40)

Looks ready

**Comment by Lucksi** [comment]
That's great, thank you for having reported this issue :)

**Comment by mendinone** [comment]
Still the Display folder is empty, only an UNTILED.txt

**Comment by Lucksi** [comment]
Mh strange let me check on my machine give me a second

**Comment by Lucksi** [comment]
On my computer works. Could you try to execute the program?

**Comment by mendinone** [comment]
IT'S DONE
Thank you very much:)

**Comment by Lucksi** [comment]
You're welcome :)

**Comment by ANUzerOTeeN7** [comment]
hello friend, can you teach me to install Osint tools created by you, I
tried to install it in Termux there was an error,,.. and can you teach me
about hacking, I really want to learn to be like you, if you don't mind
teaching me.

Pada Kha, 17 Ogo 2023, 05:03 mendinone ***@***.***> menulis:
