### ISSUE TITLE
Android error while installing 

### ISSUE THREAD

**Issue by momo-AUX1** [Lucksi/Mr.Holmes#3]
The new update of Mr.holmes broke the installation on my android device I get this error 

u0_a607@localhost  ~/Mr.Holmes   master ±  ./install_Termux.sh
./install_Termux.sh: line 6: /etc/os-release: No such file or directory
./install_Termux.sh: line 79: syntax error near unexpected token `"${GREEN}\n[+]${WHITE}SKIPPING..."'
./install_Termux.sh: line 79: `         printf("${GREEN}\n[+]${WHITE}SKIPPING...")'

Any help ?

Device : S20+ 
Android version : 12

**Comment by momo-AUX1** [comment]
The errors are less now, but there's still a token error 
install_Termux.sh: line 84: syntax error near unexpected token `;'
install_Termux.sh: line 84: `   else;'

**Comment by Lucksi** [comment]
Try to remove the ";" it is a typo mistake

**Comment by momo-AUX1** [comment]
Wheni try to remove the syntax errors it gives me am unexpected end of file error btw in the line 158 shouldn't there be a "}" to end the options function? When I try that it refuses the token

**Comment by Lucksi** [comment]
now it should be fixed i corrected the code, please let me know

**Comment by momo-AUX1** [comment]
The code is working now! Thanks amazing work by the way

**Comment by Lucksi** [comment]
Thanks to you have a nice day :)
