### ISSUE TITLE
Error install.sh

### ISSUE THREAD

**Issue by Sullyreel** [Lucksi/Mr.Holmes#30]
![IMG_6657](https://github.com/Lucksi/Mr.Holmes/assets/145237503/5cad3659-4ee7-4508-8c8a-b37f0ee848c3)

Idk why i have this error with installer

debian linux 

thx you

**Comment by Lucksi** [comment]
Hello try with sudo bash install.sh :)

**Comment by Sullyreel** [comment]
Thanks you boss

**Comment by Sullyreel** [comment]
I have do the Manual installation with WhoisXML key. But for start the tool i have This : 

![Uploading image.jpg…]()

**Comment by Sullyreel** [comment]
I have an other problem. After a good manual installation i cannot open the tool. 

I have this message, same with the Launcher.sh
![IMG_6661](https://github.com/Lucksi/Mr.Holmes/assets/145237503/9a9bbc98-db3b-410f-be06-19d71b484b00)

**Comment by Lucksi** [comment]
1 as a directory?

**Comment by Lucksi** [comment]
if you want a custom useragent list you have to provide the full path of the directory

**Comment by Lucksi** [comment]
Try to do the automatic installation and let me know if it works :)

**Comment by Sullyreel** [comment]
Automatic installation working !! 

In manual installing i typed « 1 » in useragent list 

Thanks you for the quick reply boss

**Comment by Lucksi** [comment]
You're welcome :)
