### ISSUE TITLE
Stuck at the Disclaimer

### ISSUE THREAD

**Issue by itskohler** [Lucksi/Mr.Holmes#32]
Good day, I hit Y at the disclaimer splash screen and nothing happens.

**Comment by Lucksi** [comment]
Hello can you please send me a screenshot of the problem? :)

**Comment by itskohler** [comment]
Sorry for the late reply.

![Screenshot 2023-10-24 170758](https://github.com/Lucksi/Mr.Holmes/assets/148823879/89c4c15b-71ce-44a8-b5be-571e63e81d55)

**Comment by Lucksi** [comment]
No worries have you hit enter?

**Comment by itskohler** [comment]
Yes I did. It just moves to the next line.

**Comment by Lucksi** [comment]
very strange that is the first time that i hear something similar really

**Comment by Lucksi** [comment]
Can you see please if there is a file named Display.txt in the Display folder?

**Comment by itskohler** [comment]
Yes there is, as well as a file names "UNTITLED"

**Comment by itskohler** [comment]
When I open Display.text, it just says "Display"

**Comment by Lucksi** [comment]
Mh...change that "Display" with "Desktop"

**Comment by itskohler** [comment]
Is the Display.txt file, or change the file name?

**Comment by Lucksi** [comment]
I mean edit the file Display.txt and write on it Desktop

**Comment by itskohler** [comment]
Did that, still hangs up when I type Y

**Comment by Lucksi** [comment]
Strange really strange which operating system are you using?

**Comment by itskohler** [comment]
Windows 11

**Comment by Lucksi** [comment]
Oh...i would suggest you to use a virtual machine with a Linux distribution for using this tool, with Windows 10 it worked, unfortunately i havent tried with Windows 11 but it should be the same as Windows 10

**Comment by Lucksi** [comment]
Are you running the program with Cmd?

**Comment by itskohler** [comment]
Understood! Ill give that a shot when I get home. Thank you for your help!

**Comment by itskohler** [comment]
Running it with git

**Comment by Lucksi** [comment]
No problem and try to run it with Cmd and see if that works :)

**Comment by itskohler** [comment]
That worked!

**Comment by Lucksi** [comment]
Awesome :)
