### ISSUE TITLE
Error Configuration/Agreement.txt

### ISSUE THREAD

**Issue by UserUnknowOfc** [Lucksi/Mr.Holmes#41]
(https://github.com/Lucksi/Mr.Holmes/assets/167437524/b6f3e380-411f-4e9f-ba40-fd92b298b796)
I instaled automatic, updated all requeriments

**Comment by Lucksi** [comment]
Hello, yes unfortunately this error can happen in certain circumstances, have you used the Venv installation method by any chance?

**Comment by Lucksi** [comment]
Try to run this command sudo python3 MrHolmes.py and please let me know if that solve the issue

**Comment by UserUnknowOfc** [comment]
I run this command and have other error 
(https://github.com/Lucksi/Mr.Holmes/assets/167437524/21e2d70f-269a-4670-936f-c9f7a9fdbadb)

**Comment by UserUnknowOfc** [comment]
No have this file: Agreement.txt in configuration

**Comment by Lucksi** [comment]
Ok so please go the documentation and do the Venv installation and see if something change

**Comment by Lucksi** [comment]
https://github.com/Lucksi/Mr.Holmes#heavy_check_mark-installation-linuxmac-venv-enviroment

The link above is the part of the documentation that explains how to do that

**Comment by UserUnknowOfc** [comment]
I tried the way you said but I got this error: 
└──╼ $python3 -m venv .lib_venv
Error: [Errno 13] Permission denied: '/home/user/Mr.Holmes/.lib_venv'

**Comment by Lucksi** [comment]
In case of any errors please upload a screenshot of the error

**Comment by UserUnknowOfc** [comment]
It worked, but I manually updated the phonenumbers etc. the command ip3 install -r requirements.txt was not able to update! Thak you men
