### ISSUE TITLE
UNTITLED.txt

### ISSUE THREAD

**Issue by Kaitoxic** [Lucksi/Mr.Holmes#48]
I just finished the setup and after that all the txt files was named of the folder UNTITLED.txt.

**Comment by Lucksi** [comment]
Hello, is the program working? Can you send me a screenshot of the accident please?

**Comment by Kaitoxic** [comment]
Yeah the program work :
![image](https://github.com/Lucksi/Mr.Holmes/assets/153213098/82405b6c-addc-428e-86ea-4829fe44fcf2)

But look :
![image](https://github.com/Lucksi/Mr.Holmes/assets/153213098/73b6d5c8-0d5e-4678-993d-e3f40882678c)
![image](https://github.com/Lucksi/Mr.Holmes/assets/153213098/12706e6c-52d1-4e8e-8ad5-6f32028426a5)
![image](https://github.com/Lucksi/Mr.Holmes/assets/153213098/b62cc92a-bdb8-40ff-af69-27a11e9ab288)

**Comment by Lucksi** [comment]
Yeah so all those files are normal so there are no issues :)

**Comment by Kaitoxic** [comment]
Ho so the name isn't a problem ? Like when I open the file I have no text on it

**Comment by Lucksi** [comment]
Yeah the name isn't a problem dont worry they are meant to be empty with no text

**Comment by Kaitoxic** [comment]
Ok thanks

**Comment by Kaitoxic** [comment]
But that's a bit strange like those file are meant to be edited when I use the tool or just stay untiled and void ?

**Comment by Lucksi** [comment]
Just the way they are. Actually if you want you can actually delete them
