### ISSUE TITLE
how do i open the GUI?

### ISSUE THREAD

**Issue by caseyg420** [Lucksi/Mr.Holmes#5]
I've got everything figured out except how do i open the GUI. ?

**Comment by Lucksi** [comment]
Hi, for opening the GUI you have to execute Mr. Holmes as root with the command "sudo python3 Mr.Holmes.py" and then choose option 5.
I hope this will help you :)

**Comment by caseyg420** [comment]
I will try this in just a sec. Thank you so much for responding. Hard to get feedback from creators, and I'm new to the game but learning quickly. Lol again thanks a ton and will give that a try in a sec.

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 11, 2022 at 8:51 PM, Luca ***@***.***> wrote:   


Hi, for opening the GUI you have to execute Mr. Holmes as root with the command "sudo python3 Mr.Holmes.py" and then choose option 5.
I hope this will help you :)

**Comment by Lucksi** [comment]
Your welcome, if there Is any problem, 
please let me know :)

**Comment by caseyg420** [comment]
Got the GUI to work. But the searches don't seem as accurate as just running straight through linux?  Not that big a deal, just noticed it. Also I thought I set my email up correctly to get reports, however I think I might have royally fucked that up. Any more pointers for a slight noob trying to figure it all out? Lol thanks a ton. You're awesome. 😉

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 11, 2022 at 9:12 PM, Luca ***@***.***> wrote:   


Your welcome, if there Is any problem,
please let me know :)

**Comment by Lucksi** [comment]
Thank you for saiyng that i'm awesome i really appreciate It, have a nice Day and thanks again 🙂
