### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by p41n1nurnl** [Lucksi/Mr.Holmes#50]
UnboundLocalError: cannot access local variable 'email' where it is not associated with a value
![изображение](https://github.com/Lucksi/Mr.Holmes/assets/174846786/4827162d-e05f-4fd5-b714-f6a767fd2d4a)

**Comment by Lucksi** [comment]
Hello. Thank you for having pointed out this issue. It should be fixed now

**Comment by p41n1nurnl** [comment]
Thank you for quick answer and quick fix!
